### ISSUE TITLE
Create Initial Project structures

### ISSUE THREAD

**Issue by cheahkhing** [coding-sig/Swift#1]
Need to setup project structure with Angular4, SCSS, and various webpack configurations

**Comment by cheahkhing** [comment]
Done with 47d2eb070058b02cea1924eb0c95a9eafdbef22a

**Comment by weijyewang** [comment]
@cheahkhing  How does one run the localhost for the project app? Tried with "ng serve" from angular-cli with no luck, and did not spot any webpack config in the project either.

**Comment by cheahkhing** [comment]
@weijyewang huh? it works for me. you got do npm install right? it should work. i'll try clone a fresh copy and see.

**Comment by cheahkhing** [comment]
yea, quite sure it works. I cloned a fresh copy and npm install, ng-serve, everything works.
Probably you need to check your ng-cli:
![image](https://user-images.githubusercontent.com/563883/29486928-03583726-8524-11e7-9185-5508f448c186.png)

**Comment by weijyewang** [comment]
my bad sorry. after running "ng --version", I realize that my angular-cli was very outdated, it was the 1.0 beta version LOL. By the way, it seems like i need to update my node.js as well.
![image](https://user-images.githubusercontent.com/8890603/29488543-ee91d4f2-853f-11e7-96e1-4769e3fd0026.png)

**Comment by weijyewang** [comment]
Just want to update - ng serve is working fine now after installing the latest angular cli. Thanks for the help :)
