### ISSUE TITLE
Design project tagline and logo

### ISSUE THREAD

**Issue by cheahkhing** [coding-sig/Swift#2]
Swift should have its own tagline and logo

**Comment by weijyewang** [comment]
Where should I add it to?

**Comment by cheahkhing** [comment]
@weijyewang just add it to the README? The readme right now a bit empty. Need to put more stuff.

**Comment by weijyewang** [comment]
@cheahkhing roger that.

**Comment by weijyewang** [comment]
Done with https://github.com/coding-sig/Swift/commit/b2f3adbaf45c4d0a945da7530b2de11904f47a0c

**Comment by weijyewang** [comment]
The team will have to pick and choose a tag line and a logo from the draft (README.md)
